# Generated by Django 5.2.14 on 2026-05-22 09:51

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='hiremerequest',
            name='phone',
            field=models.CharField(blank=True, help_text='Include international code, e.g., +1234567890', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated price in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon for the tech stack/project', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name or class (e.g. fa-brands fa-python)', max_length=100),
        ),
        migrations.AlterField(
            model_name='hiremerequest',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated budget in USD', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hiremerequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Client/Company Name'),
        ),
        migrations.AlterField(
            model_name='hiremerequest',
            name='project_description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='challenge_solution',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Challenge Solution'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='Comma-separated values (e.g. React, Django, PostgreSQL)', max_length=500),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.project')),
            ],
        ),
    ]
