# Generated by Django 5.2.14 on 2026-05-22 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_skill_proficiency_hiremerequest_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, choices=[('Activity', 'Activity'), ('Archive', 'Archive'), ('Award', 'Award'), ('Book', 'Book'), ('Briefcase', 'Briefcase'), ('CheckCircle', 'CheckCircle'), ('Cloud', 'Cloud'), ('CloudCog', 'CloudCog'), ('Code', 'Code'), ('Code2', 'Code2'), ('Cpu', 'Cpu'), ('Database', 'Database'), ('FileText', 'FileText'), ('Globe', 'Globe'), ('Layers', 'Layers'), ('Layout', 'Layout'), ('LayoutTemplate', 'LayoutTemplate'), ('Monitor', 'Monitor'), ('Rocket', 'Rocket'), ('Server', 'Server'), ('ServerCog', 'ServerCog'), ('Shield', 'Shield'), ('ShieldCheck', 'ShieldCheck'), ('Smartphone', 'Smartphone'), ('Star', 'Star'), ('Terminal', 'Terminal'), ('Users', 'Users'), ('Wrench', 'Wrench'), ('PenTool', 'PenTool'), ('PenBox', 'PenBox'), ('Laptop', 'Laptop')], help_text='Select a Lucide icon', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Project Categories',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, choices=[('Activity', 'Activity'), ('Archive', 'Archive'), ('Award', 'Award'), ('Book', 'Book'), ('Briefcase', 'Briefcase'), ('CheckCircle', 'CheckCircle'), ('Cloud', 'Cloud'), ('CloudCog', 'CloudCog'), ('Code', 'Code'), ('Code2', 'Code2'), ('Cpu', 'Cpu'), ('Database', 'Database'), ('FileText', 'FileText'), ('Globe', 'Globe'), ('Layers', 'Layers'), ('Layout', 'Layout'), ('LayoutTemplate', 'LayoutTemplate'), ('Monitor', 'Monitor'), ('Rocket', 'Rocket'), ('Server', 'Server'), ('ServerCog', 'ServerCog'), ('Shield', 'Shield'), ('ShieldCheck', 'ShieldCheck'), ('Smartphone', 'Smartphone'), ('Star', 'Star'), ('Terminal', 'Terminal'), ('Users', 'Users'), ('Wrench', 'Wrench'), ('PenTool', 'PenTool'), ('PenBox', 'PenBox'), ('Laptop', 'Laptop')], help_text='Icon for the tech stack/project', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, choices=[('Activity', 'Activity'), ('Archive', 'Archive'), ('Award', 'Award'), ('Book', 'Book'), ('Briefcase', 'Briefcase'), ('CheckCircle', 'CheckCircle'), ('Cloud', 'Cloud'), ('CloudCog', 'CloudCog'), ('Code', 'Code'), ('Code2', 'Code2'), ('Cpu', 'Cpu'), ('Database', 'Database'), ('FileText', 'FileText'), ('Globe', 'Globe'), ('Layers', 'Layers'), ('Layout', 'Layout'), ('LayoutTemplate', 'LayoutTemplate'), ('Monitor', 'Monitor'), ('Rocket', 'Rocket'), ('Server', 'Server'), ('ServerCog', 'ServerCog'), ('Shield', 'Shield'), ('ShieldCheck', 'ShieldCheck'), ('Smartphone', 'Smartphone'), ('Star', 'Star'), ('Terminal', 'Terminal'), ('Users', 'Users'), ('Wrench', 'Wrench'), ('PenTool', 'PenTool'), ('PenBox', 'PenBox'), ('Laptop', 'Laptop')], help_text='Select a Lucide icon', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.projectcategory'),
        ),
    ]
