# Generated by Django 5.2.14 on 2026-05-24 07:50

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projectcategory_alter_project_icon_alter_skill_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(choices=[('devicon-python-plain', 'Python'), ('devicon-django-plain', 'Django'), ('devicon-react-original', 'React'), ('devicon-nextjs-plain', 'Next.js'), ('devicon-docker-plain', 'Docker'), ('devicon-postgresql-plain', 'PostgreSQL'), ('devicon-nginx-original', 'Nginx'), ('devicon-cloudflare-plain', 'Cloudflare'), ('devicon-ubuntu-plain', 'Ubuntu'), ('devicon-linux-plain', 'Linux'), ('devicon-git-plain', 'Git'), ('devicon-github-original', 'GitHub'), ('devicon-javascript-plain', 'JavaScript'), ('devicon-typescript-plain', 'TypeScript'), ('devicon-nodejs-plain-wordmark', 'Node.js'), ('devicon-html5-plain', 'HTML5'), ('devicon-css3-plain', 'CSS3'), ('devicon-tailwindcss-original', 'Tailwind CSS'), ('devicon-redis-plain', 'Redis'), ('devicon-mysql-plain', 'MySQL'), ('devicon-amazonwebservices-plain-wordmark', 'AWS'), ('devicon-googlecloud-plain', 'Google Cloud')], help_text='Select a tech icon', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='challenge_solution',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_fa',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_nl',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_nl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_fa',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_nl',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_fa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_nl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.CharField(blank=True, choices=[('Activity', 'Activity'), ('Archive', 'Archive'), ('Award', 'Award'), ('Book', 'Book'), ('Briefcase', 'Briefcase'), ('CheckCircle', 'CheckCircle'), ('Cloud', 'Cloud'), ('CloudCog', 'CloudCog'), ('Code', 'Code'), ('Code2', 'Code2'), ('Cpu', 'Cpu'), ('Database', 'Database'), ('FileText', 'FileText'), ('Globe', 'Globe'), ('Layers', 'Layers'), ('Layout', 'Layout'), ('LayoutTemplate', 'LayoutTemplate'), ('Monitor', 'Monitor'), ('Rocket', 'Rocket'), ('Server', 'Server'), ('ServerCog', 'ServerCog'), ('Shield', 'Shield'), ('ShieldCheck', 'ShieldCheck'), ('Smartphone', 'Smartphone'), ('Star', 'Star'), ('Terminal', 'Terminal'), ('Users', 'Users'), ('Wrench', 'Wrench'), ('PenTool', 'PenTool'), ('PenBox', 'PenBox'), ('Laptop', 'Laptop'), ('devicon-python-plain', 'Python'), ('devicon-django-plain', 'Django'), ('devicon-react-original', 'React'), ('devicon-nextjs-plain', 'Next.js'), ('devicon-docker-plain', 'Docker'), ('devicon-postgresql-plain', 'PostgreSQL'), ('devicon-nginx-original', 'Nginx'), ('devicon-cloudflare-plain', 'Cloudflare'), ('devicon-ubuntu-plain', 'Ubuntu'), ('devicon-linux-plain', 'Linux'), ('devicon-git-plain', 'Git'), ('devicon-github-original', 'GitHub'), ('devicon-javascript-plain', 'JavaScript'), ('devicon-typescript-plain', 'TypeScript'), ('devicon-nodejs-plain-wordmark', 'Node.js'), ('devicon-html5-plain', 'HTML5'), ('devicon-css3-plain', 'CSS3'), ('devicon-tailwindcss-original', 'Tailwind CSS'), ('devicon-redis-plain', 'Redis'), ('devicon-mysql-plain', 'MySQL'), ('devicon-amazonwebservices-plain-wordmark', 'AWS'), ('devicon-googlecloud-plain', 'Google Cloud')], help_text='Icon for the tech stack/project', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, choices=[('Activity', 'Activity'), ('Archive', 'Archive'), ('Award', 'Award'), ('Book', 'Book'), ('Briefcase', 'Briefcase'), ('CheckCircle', 'CheckCircle'), ('Cloud', 'Cloud'), ('CloudCog', 'CloudCog'), ('Code', 'Code'), ('Code2', 'Code2'), ('Cpu', 'Cpu'), ('Database', 'Database'), ('FileText', 'FileText'), ('Globe', 'Globe'), ('Layers', 'Layers'), ('Layout', 'Layout'), ('LayoutTemplate', 'LayoutTemplate'), ('Monitor', 'Monitor'), ('Rocket', 'Rocket'), ('Server', 'Server'), ('ServerCog', 'ServerCog'), ('Shield', 'Shield'), ('ShieldCheck', 'ShieldCheck'), ('Smartphone', 'Smartphone'), ('Star', 'Star'), ('Terminal', 'Terminal'), ('Users', 'Users'), ('Wrench', 'Wrench'), ('PenTool', 'PenTool'), ('PenBox', 'PenBox'), ('Laptop', 'Laptop'), ('devicon-python-plain', 'Python'), ('devicon-django-plain', 'Django'), ('devicon-react-original', 'React'), ('devicon-nextjs-plain', 'Next.js'), ('devicon-docker-plain', 'Docker'), ('devicon-postgresql-plain', 'PostgreSQL'), ('devicon-nginx-original', 'Nginx'), ('devicon-cloudflare-plain', 'Cloudflare'), ('devicon-ubuntu-plain', 'Ubuntu'), ('devicon-linux-plain', 'Linux'), ('devicon-git-plain', 'Git'), ('devicon-github-original', 'GitHub'), ('devicon-javascript-plain', 'JavaScript'), ('devicon-typescript-plain', 'TypeScript'), ('devicon-nodejs-plain-wordmark', 'Node.js'), ('devicon-html5-plain', 'HTML5'), ('devicon-css3-plain', 'CSS3'), ('devicon-tailwindcss-original', 'Tailwind CSS'), ('devicon-redis-plain', 'Redis'), ('devicon-mysql-plain', 'MySQL'), ('devicon-amazonwebservices-plain-wordmark', 'AWS'), ('devicon-googlecloud-plain', 'Google Cloud')], help_text='Select an icon', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stacks',
            field=models.ManyToManyField(blank=True, related_name='projects', to='api.techstack'),
        ),
    ]
