# Generated by Django 5.2.14 on 2026-06-10 08:13

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_techstack_remove_project_challenge_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_de',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_de',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_de',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_de',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
