# Generated by Django 5.2.14 on 2026-07-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_description_de_project_title_de_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_stacks',
        ),
        migrations.DeleteModel(
            name='TechStack',
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stacks',
            field=models.JSONField(blank=True, default=list, help_text="List of tech stack names, e.g. ['React', 'Django']"),
        ),
    ]
