# Generated by Django 5.2.14 on 2026-07-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_skill_remove_project_tech_stacks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_stacks',
            field=models.JSONField(blank=True, default=list, help_text="List of tech stack names, e.g. ['React', 'Django']", null=True),
        ),
    ]
