# docker-compose.yml
name: portfolio-saas

services:
  db:
    image: postgres:16-alpine
    container_name: portfolio_db
    restart: unless-stopped
    env_file:
      - .env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  backend:
    build:
      context: ./backend
    container_name: portfolio_backend
    restart: unless-stopped
    env_file:
      - .env.local
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis

  redis:
    image: redis:7-alpine
    container_name: portfolio_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: ./backend
    container_name: portfolio_celery
    restart: unless-stopped
    env_file:
      - .env.local
    volumes:
      - ./backend:/app
    command: celery -A config worker -l info
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      network: host
    container_name: portfolio_frontend
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "80:80"
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  postgres_data:
    name: portfolio_pg_data